
#ifndef __FRAMEWORKERR_H__
#define __FRAMEWORKERR_H__

#include <carerr.h>

#define FAMILY_FRAMEWORK        0x30    // Framework Error codes

#define FRAMEWORK_ERROR(c)      MAKE_ECODE(SEVERITY_ERROR, FAMILY_FRAMEWORK, c)
#define FRAMEWORK_SUCCESS(c)    MAKE_SUCCESS(FAMILY_FRAMEWORK, c)

//==========================================================================
// Elastos Framework error codes (Family: 0x20)
#define E_REMOTE_EXCEPTION              FRAMEWORK_ERROR(0x01)
//#define E_SECURITY_EXCEPTION            FRAMEWORK_ERROR(0x02)
#define E_LAUNCH_EXCEPTION              FRAMEWORK_ERROR(0x03)
//#define E_RUNTIME_EXCEPTION             FRAMEWORK_ERROR(0x05)
//#define E_ILLEGAL_STATE_EXCEPTION       FRAMEWORK_ERROR(0x06)
#define E_BAD_TOKEN_EXCEPTION           FRAMEWORK_ERROR(0x08)
#define E_CALLED_FROM_WRONG_THREAD_EXCEPTION    FRAMEWORK_ERROR(0x09)
//#define E_UNSUPPORTED_OPERATION_EXCEPTION       FRAMEWORK_ERROR(0x0A)
#define E_NOT_FOUND_EXCEPTION           FRAMEWORK_ERROR(0x0B)
#define E_BAD_SURFACE_TYPE_EXCEPTION    FRAMEWORK_ERROR(0x0D)
#define E_INFLATE_EXCEPTION             FRAMEWORK_ERROR(0x10)
// #define E_NO_SUCH_METHOD_EXCEPTION      FRAMEWORK_ERROR(0x11)
#define E_CLASS_NOT_FOUND_EXCEPTION     FRAMEWORK_ERROR(0x12)
#define E_MALFORMED_MIME_TYPE_EXCEPTION FRAMEWORK_ERROR(0x13)

//sqlite
#define E_SQLITE_EXCEPTION FRAMEWORK_ERROR(0x14)
#define E_SQLITE_DATABASE_CORRUPT_EXCEPTION FRAMEWORK_ERROR(0x15)
#define E_SQLITE_MISUSE_EXCEPTION FRAMEWORK_ERROR(0x16)
#define E_SQLITE_ABORT_EXCEPTION FRAMEWORK_ERROR(0x17)
#define E_SQLITE_CONSTRAINT_EXCEPTION FRAMEWORK_ERROR(0x18)
#define E_SQLITE_FULL_EXCEPTION FRAMEWORK_ERROR(0x19)
#define E_SQLITE_DISK_IO_EXCEPTION FRAMEWORK_ERROR(0x20)

//database
#define E_SQL_EXCEPTION FRAMEWORK_ERROR(0x21)
#define E_CURSOR_INDEX_OUT_OF_BOUNDS_EXCEPTION FRAMEWORK_ERROR(0x22)
#define E_STALE_DATA_EXCEPTION FRAMEWORK_ERROR(0x23)


#endif //__FRAMEWORKERR_H__
